### ISSUE TITLE
[Features] TODO List

### ISSUE THREAD

**Issue by smartcatboy** [Aurora-Admin-Panel/compose#37]
TODO List

- [ ] frontend disable haproxy & iptables
- [ ] frontend xray support
- [ ] frontend app update
- [ ] frontend reboot & delete all rules of a server
- [ ] other batch port operations: export & import all rules of a server （maybe dump to json format encrypted by base64?）
- [ ] true port limitation (disable adding or changing forward rules when reach port limitation or just disable user)
- [ ] nginx forward
- [ ] ipv6 ssh support (docker-compose.yml)
